### ISSUE TITLE
Add screenshot in Result section

### ISSUE THREAD

**Issue by sergiomarotco** [slsa-framework/azure-devops-demo#9]
Can u add screenshot in [Result section](https://github.com/slsa-framework/azure-devops-demo#results) ?

**Comment by gattjoe** [comment]
Apologies for the delay, will do this tomorrow.

**Comment by sergiomarotco** [comment]
Awesome!

**Comment by gattjoe** [comment]
So I remember this now, I didn't publish a screenshot of the output because its essentially a file named build.provenance.  So instead an example is in this repository here: https://github.com/slsa-framework/azure-devops-demo/blob/main/examples/build.provenance

I'll close this issue for now, but open to suggestions on how to improve.

**Comment by sergiomarotco** [comment]
@gattjoe may be add this link to Result section?
